#!/usr/bin/env python3
"""Assemble the 57 game symbols and emit the Dart asset table.

Symbol ids 0..55 map to real Tollywood sticker art (downscaled, padded to
a square, RGBA). Id 56 has no asset and falls back to the painted
placeholder in SymbolView -- one distinct symbol among 56 photos, which
keeps every symbol visually unambiguous without duplicating art.

Sources, in id order:
  0..27   assets/stickers/tollywood/*.png        (alphabetical)
  28..31  assets/stickers/extracted/p4-*.png
  32..39  assets/stickers/extracted/p81-*.png
  40..47  assets/stickers/extracted/p82-*.png
  48..55  assets/stickers/extracted/p83-*.png

Outputs:
  assets/symbols/00.png .. 55.png   (max 480px, square canvas, transparent)
  lib/deck/symbol_assets.dart
"""
from __future__ import annotations

import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
STK = ROOT / "assets" / "stickers"
OUT = ROOT / "assets" / "symbols"
DART = ROOT / "lib" / "deck" / "symbol_assets.dart"

SIZE = 480
COUNT = 57  # ids 0..56; id 56 is the painted fallback (no file)


def sources() -> list[pathlib.Path]:
    src: list[pathlib.Path] = []
    src += sorted((STK / "tollywood").glob("*.png"))
    for prefix in ("p4", "p81", "p82", "p83"):
        src += sorted((STK / "extracted").glob(f"{prefix}-*.png"))
    return src


_FILL = 0.86  # fraction of the square canvas the content spans


def normalise(img: Image.Image) -> Image.Image:
    """Tight-crop to visible content, then centre it on a transparent square
    so its longest side spans ~86% of the canvas.

    Squaring every symbol gives them a consistent on-card size regardless of
    the source aspect ratio (a wide two-person sticker and a tall single
    figure end up occupying the same slot area under `BoxFit.contain`).
    """
    img = img.convert("RGBA")
    bbox = img.split()[3].getbbox()
    if bbox:
        m = 4
        img = img.crop((
            max(bbox[0] - m, 0),
            max(bbox[1] - m, 0),
            min(bbox[2] + m, img.width),
            min(bbox[3] + m, img.height),
        ))
    target = int(SIZE * _FILL)
    img.thumbnail((target, target), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(img, ((SIZE - img.width) // 2, (SIZE - img.height) // 2), img)
    return canvas


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.png"):
        old.unlink()

    src = sources()
    real = COUNT - 1  # 56
    if len(src) < real:
        raise SystemExit(f"need {real} source stickers, found {len(src)}")
    src = src[:real]

    for i, path in enumerate(src):
        normalise(Image.open(path)).save(OUT / f"{i:02d}.png", optimize=True)

    entries = ",\n".join(
        f'  "assets/symbols/{i:02d}.png"' for i in range(real)
    )
    DART.write_text(
        "// GENERATED by tool/build_symbols.py -- do not edit by hand.\n"
        "//\n"
        "// Asset path for each symbol id, or null to fall back to the\n"
        "// painted placeholder in SymbolView. Length is always 57.\n"
        "\n"
        "const List<String?> kSymbolAssets = <String?>[\n"
        f"{entries},\n"
        "  null, // id 56: painted fallback\n"
        "];\n"
    )

    total = sum(f.stat().st_size for f in OUT.glob("*.png"))
    print(f"wrote {real} symbols to {OUT.relative_to(ROOT)} ({total / 1e6:.1f} MB)")
    print(f"wrote {DART.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
