#!/usr/bin/env python3
"""Assemble the 57 game symbols and emit the Dart asset table.

All 57 symbol ids map to real Tollywood sticker art (downscaled, padded
to a square, RGBA) -- no painted placeholder.

Sources, in id order:
  assets/stickers/tollywood/*.png        (alphabetical)
  assets/stickers/extracted/p4-*.png
  assets/stickers/extracted/p81-*.png
  assets/stickers/extracted/p82-*.png
  assets/stickers/extracted/p83-*.png

Outputs:
  assets/symbols/00.png .. 56.png   (max 480px, square canvas, transparent)
  lib/deck/symbol_assets.dart
"""
from __future__ import annotations

import argparse
import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
STK = ROOT / "assets" / "stickers"
OUT = ROOT / "assets" / "symbols"
DART = ROOT / "lib" / "deck" / "symbol_assets.dart"

SIZE = 480
COUNT = 57  # ids 0..56, all backed by real art


def sources() -> list[pathlib.Path]:
    src: list[pathlib.Path] = []
    src += sorted((STK / "tollywood").glob("*.png"))
    for prefix in ("p4", "p81", "p82", "p83"):
        src += sorted((STK / "extracted").glob(f"{prefix}-*.png"))
    return src


_FILL = 0.86  # fraction of the square canvas the content spans


def normalise(img: Image.Image, square: bool = True) -> Image.Image:
    """Tight-crop to visible content, then scale it down.

    When `square`, centre the crop on a transparent square canvas so its
    longest side spans ~86% of the canvas -- this gives every symbol a
    consistent on-card footprint regardless of source aspect ratio (a wide
    two-person sticker and a tall single figure end up occupying the same
    slot area under `BoxFit.contain`). When not `square`, just cap the
    longest side at SIZE and keep the source aspect ratio, no padding.
    """
    img = img.convert("RGBA")
    bbox = img.split()[3].getbbox()
    if bbox:
        m = 4
        img = img.crop((
            max(bbox[0] - m, 0),
            max(bbox[1] - m, 0),
            min(bbox[2] + m, img.width),
            min(bbox[3] + m, img.height),
        ))
    if not square:
        img.thumbnail((SIZE, SIZE), Image.Resampling.LANCZOS)
        return img
    target = int(SIZE * _FILL)
    img.thumbnail((target, target), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(img, ((SIZE - img.width) // 2, (SIZE - img.height) // 2), img)
    return canvas


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-square",
        action="store_true",
        help="skip padding to a square canvas; keep each sticker's own aspect ratio",
    )
    args = parser.parse_args()
    square = not args.no_square

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.png"):
        old.unlink()

    src = sources()
    if len(src) < COUNT:
        raise SystemExit(f"need {COUNT} source stickers, found {len(src)}")
    src = src[:COUNT]

    for i, path in enumerate(src):
        normalise(Image.open(path), square=square).save(
            OUT / f"{i:02d}.png", optimize=True
        )

    entries = ",\n".join(
        f'  "assets/symbols/{i:02d}.png"' for i in range(COUNT)
    )
    DART.write_text(
        "// GENERATED by tool/build_symbols.py -- do not edit by hand.\n"
        "//\n"
        "// Asset path for each symbol id. Length is always 57.\n"
        "\n"
        "const List<String> kSymbolAssets = <String>[\n"
        f"{entries},\n"
        "];\n"
    )

    total = sum(f.stat().st_size for f in OUT.glob("*.png"))
    print(f"wrote {COUNT} symbols to {OUT.relative_to(ROOT)} ({total / 1e6:.1f} MB)")
    print(f"wrote {DART.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
